/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyRestaurant360RouteImport } from './routes/why-restaurant360'
import { Route as SettlementRouteImport } from './routes/settlement'
import { Route as RequestDemoRouteImport } from './routes/request-demo'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PosRouteImport } from './routes/pos'
import { Route as OrderManagementRouteImport } from './routes/order-management'
import { Route as KitchenKotRouteImport } from './routes/kitchen-kot'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AccountsFinanceRouteImport } from './routes/accounts-finance'
import { Route as IndexRouteImport } from './routes/index'

const WhyRestaurant360Route = WhyRestaurant360RouteImport.update({
  id: '/why-restaurant360',
  path: '/why-restaurant360',
  getParentRoute: () => rootRouteImport,
} as any)
const SettlementRoute = SettlementRouteImport.update({
  id: '/settlement',
  path: '/settlement',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestDemoRoute = RequestDemoRouteImport.update({
  id: '/request-demo',
  path: '/request-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderManagementRoute = OrderManagementRouteImport.update({
  id: '/order-management',
  path: '/order-management',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenKotRoute = KitchenKotRouteImport.update({
  id: '/kitchen-kot',
  path: '/kitchen-kot',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsFinanceRoute = AccountsFinanceRouteImport.update({
  id: '/accounts-finance',
  path: '/accounts-finance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts-finance': typeof AccountsFinanceRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/inventory': typeof InventoryRoute
  '/kitchen-kot': typeof KitchenKotRoute
  '/order-management': typeof OrderManagementRoute
  '/pos': typeof PosRoute
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/request-demo': typeof RequestDemoRoute
  '/settlement': typeof SettlementRoute
  '/why-restaurant360': typeof WhyRestaurant360Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts-finance': typeof AccountsFinanceRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/inventory': typeof InventoryRoute
  '/kitchen-kot': typeof KitchenKotRoute
  '/order-management': typeof OrderManagementRoute
  '/pos': typeof PosRoute
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/request-demo': typeof RequestDemoRoute
  '/settlement': typeof SettlementRoute
  '/why-restaurant360': typeof WhyRestaurant360Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts-finance': typeof AccountsFinanceRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/inventory': typeof InventoryRoute
  '/kitchen-kot': typeof KitchenKotRoute
  '/order-management': typeof OrderManagementRoute
  '/pos': typeof PosRoute
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/request-demo': typeof RequestDemoRoute
  '/settlement': typeof SettlementRoute
  '/why-restaurant360': typeof WhyRestaurant360Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts-finance'
    | '/contact'
    | '/features'
    | '/inventory'
    | '/kitchen-kot'
    | '/order-management'
    | '/pos'
    | '/pricing'
    | '/reports'
    | '/request-demo'
    | '/settlement'
    | '/why-restaurant360'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts-finance'
    | '/contact'
    | '/features'
    | '/inventory'
    | '/kitchen-kot'
    | '/order-management'
    | '/pos'
    | '/pricing'
    | '/reports'
    | '/request-demo'
    | '/settlement'
    | '/why-restaurant360'
  id:
    | '__root__'
    | '/'
    | '/accounts-finance'
    | '/contact'
    | '/features'
    | '/inventory'
    | '/kitchen-kot'
    | '/order-management'
    | '/pos'
    | '/pricing'
    | '/reports'
    | '/request-demo'
    | '/settlement'
    | '/why-restaurant360'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsFinanceRoute: typeof AccountsFinanceRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  InventoryRoute: typeof InventoryRoute
  KitchenKotRoute: typeof KitchenKotRoute
  OrderManagementRoute: typeof OrderManagementRoute
  PosRoute: typeof PosRoute
  PricingRoute: typeof PricingRoute
  ReportsRoute: typeof ReportsRoute
  RequestDemoRoute: typeof RequestDemoRoute
  SettlementRoute: typeof SettlementRoute
  WhyRestaurant360Route: typeof WhyRestaurant360Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-restaurant360': {
      id: '/why-restaurant360'
      path: '/why-restaurant360'
      fullPath: '/why-restaurant360'
      preLoaderRoute: typeof WhyRestaurant360RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settlement': {
      id: '/settlement'
      path: '/settlement'
      fullPath: '/settlement'
      preLoaderRoute: typeof SettlementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-demo': {
      id: '/request-demo'
      path: '/request-demo'
      fullPath: '/request-demo'
      preLoaderRoute: typeof RequestDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-management': {
      id: '/order-management'
      path: '/order-management'
      fullPath: '/order-management'
      preLoaderRoute: typeof OrderManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-kot': {
      id: '/kitchen-kot'
      path: '/kitchen-kot'
      fullPath: '/kitchen-kot'
      preLoaderRoute: typeof KitchenKotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts-finance': {
      id: '/accounts-finance'
      path: '/accounts-finance'
      fullPath: '/accounts-finance'
      preLoaderRoute: typeof AccountsFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsFinanceRoute: AccountsFinanceRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  InventoryRoute: InventoryRoute,
  KitchenKotRoute: KitchenKotRoute,
  OrderManagementRoute: OrderManagementRoute,
  PosRoute: PosRoute,
  PricingRoute: PricingRoute,
  ReportsRoute: ReportsRoute,
  RequestDemoRoute: RequestDemoRoute,
  SettlementRoute: SettlementRoute,
  WhyRestaurant360Route: WhyRestaurant360Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
